version: '3.8'

services:
  backend:
    build:
      context: ./cotizador-backend
    container_name: cotizador-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: cotizador-redis
    ports:
      - "6379:6379"
