server:
  port: 8081

spring:
  application:
    name: cotizador

 
  r2dbc:
    url: ''
    username: ''
    password: ''
    
  
  data:
    redis:
      host: localhost
      port: 6379

spring.main:
  web-application-type: reactive

springdoc:
  swagger-ui:
    path: /swagger-ui.html

