server:
  port: 8081

spring:
  application:
    name: cotizador

  # Configuración de la conexión a la base de datos PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/cotizador
    username: postgres
    password: ""
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10


  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true  
    database-platform: org.hibernate.dialect.PostgreSQLDialect    

      

  r2dbc:
    url: ''
    username: ''
    password: ''
    
  
  data:
    redis:
      host: localhost
      port: 6379

spring.main:
  web-application-type: reactive

springdoc:
  swagger-ui:
    path: /swagger-ui.html

